# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: 869456089606.dkr.ecr.eu-central-1.amazonaws.com/application/gitpod/workspace-full:latest

jetbrains:
    intellij:
        plugins:
            - cucumber-javascript